version: "3.3"
services:
    database:
        image: "mongo:latest"
        ports:
            - "27017:27017"
        container_name: "airQmap_db"
        volumes:
            - "./data/db:/data/db"