version: "3.3"
services:
    database:
        image: "mongo:latest"
        ports:
            - "27017:27017"
        container_name: "airQmap_db"
        volumes:
            - "./data/db:/data/db"
    app:
        build: .
        image: airqmap_app_img
        container_name: airqmap_app
        ports:
            - 5000:5000
        depends_on: 
            - database